# -*- coding: utf-8 -*-
"""VariáveisEstado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148188lPHdFjBOOThVUeS3W0g0flfjnPO

Conversão de sistemas com coeficientes numéricos entre função de transferência e representação em espaço de estados.
"""

import scipy.signal

G = scipy.signal.lti(1, [1, 1])
G

#Este objeto nos permite acessar o numerador e o denominador
G.num, G.den

#Para converter para espaço de estados, podemos usar o método .to_ss()
Gss = G.to_ss()
Gss.A, Gss.B, Gss.C, Gss.D

#Podemos construir outro objeto usando as matrizes de espaço de estados em vez da forma de Laplace
G2ss = scipy.signal.lti(Gss.A, Gss.B, Gss.C, Gss.D)
G2ss

#Podemos converter para a forma de função de transferência usando .to_tf()
G2 = G2ss.to_tf()

#Agora podemos acessar novamente o numerador e o denominador:
G2.num, G2.den